### ISSUE TITLE
Add On-Hover animation on handlers 

### ISSUE THREAD

**Issue by Snailedlt** [SplitScreen-Me/splitscreenme-hub#31]
Add on-hover animations to the handlers, like we have on the handlers here: https://www.splitscreen.me/

CSS
```css
.handlers {
  transition: transform .2s; /* Animation */
  margin: 0 auto;
}

.handlers:hover {
  transform: scale(1.1); /* (110% zoom - Note: if the zoom is too large, it will go outside of the viewport) */
}
```
